version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database/init.schema.sql:/docker-entrypoint-initdb.d/init.schema.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # backend:
  #   build: ./backend
  #   container_name: my_flask_app
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./backend:/app

volumes:
  pgdata: