CREATE TABLE "Car" (
  "Car_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Brand" text NOT NULL,
  "Model" text NOT NULL,
  "Color" text NOT NULL,
  "Mileage" integer NOT NULL,
  "Price" integer NOT NULL,
  "Car_condition_ID" integer NOT NULL,
  "Car_dealer_ID" integer NOT NULL
);

CREATE TABLE "Car_condition" (
  "Car_condition_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Condition" name NOT NULL
);

CREATE TABLE "Car_dealer" (
  "Car_dealer_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Name" text NOT NULL,
  "Address_ID" integer NOT NULL
);

CREATE TABLE "Address" (
  "Address_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Postcode" text NOT NULL,
  "Street" text NOT NULL,
  "Street_number" integer NOT NULL,
  "City_ID" integer NOT NULL
);

CREATE TABLE "City" (
  "City_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Name" text NOT NULL,
  "Country" text NOT NULL
);

CREATE TABLE "Client" (
  "Client_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Name" text NOT NULL,
  "Surname" text NOT NULL,
  "Gender" text NOT NULL,
  "Mail" text NOT NULL,
  "Phone" text NOT NULL
);

CREATE TABLE "Transaction" (
  "Transaction_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Date" date NOT NULL,
  "Value" integer NOT NULL,
  "Client_ID" integer NOT NULL,
  "Employee_ID" integer NOT NULL,
  "Transaction_type_ID" integer NOT NULL,
  "Invoice_ID" integer UNIQUE
);

CREATE TABLE "Employee" (
  "Employee_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  "Name" text NOT NULL,
  "Surname" text NOT NULL,
  "Gender" text NOT NULL,
  "Salary" integer,
  "Date_of_birth" date NOT NULL,
  "Phone_number" text,
  "Employee_status_ID" integer NOT NULL,
  "Car_dealer_ID" integer NOT NULL,
  "Login_credentials_ID" integer NOT NULL
);

CREATE TABLE "Employee_status" (
  "Employee_status_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Status_name" text NOT NULL
);

CREATE TABLE "Position" (
  "Position_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Name" text NOT NULL,
  "Min_salary" integer,
  "Max_salary" integer
);

CREATE TABLE "Position_history" (
  "Position_history_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Date_start" date NOT NULL,
  "Date_end" date,
  "Position_ID" integer NOT NULL,
  "Employee_ID" integer NOT NULL
);

CREATE TABLE "Transaction_type" (
  "Transaction_type_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Name" text NOT NULL
);

CREATE TABLE "Invoice" (
  "Invoice_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Status" text NOT NULL,
  "Issue_date" date,
  "NIP" bigint NOT NULL
);

CREATE TABLE "Employee_stats" (
  "Year" integer,
  "Month" integer,
  "Employee_ID" integer,
  "Sales_sum" integer NOT NULL,
  PRIMARY KEY ("Year", "Month", "Employee_ID")
);

CREATE TABLE "Login_credentials" (
  "Login_credentials_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  "Login" text NOT NULL,
  "Password" text NOT NULL
);

ALTER TABLE "Car" ADD FOREIGN KEY ("Car_condition_ID")
REFERENCES "Car_condition" ("Car_condition_ID") ON DELETE CASCADE;

ALTER TABLE "Car" ADD FOREIGN KEY ("Car_dealer_ID") 
REFERENCES "Car_dealer" ("Car_dealer_ID") ON DELETE CASCADE;

ALTER TABLE "Transaction" ADD FOREIGN KEY ("Client_ID") 
REFERENCES "Client" ("Client_ID") ON DELETE CASCADE;

ALTER TABLE "Transaction" ADD FOREIGN KEY ("Employee_ID") 
REFERENCES "Employee" ("Employee_ID") ON DELETE CASCADE;

ALTER TABLE "Address" ADD FOREIGN KEY ("City_ID") 
REFERENCES "City" ("City_ID") ON DELETE CASCADE;

ALTER TABLE "Employee" ADD FOREIGN KEY ("Employee_status_ID") 
REFERENCES "Employee_status" ("Employee_status_ID") ON DELETE CASCADE;

ALTER TABLE "Employee" ADD FOREIGN KEY ("Car_dealer_ID") 
REFERENCES "Car_dealer" ("Car_dealer_ID") ON DELETE CASCADE;

ALTER TABLE "Position_history" ADD FOREIGN KEY ("Employee_ID") 
REFERENCES "Employee" ("Employee_ID") ON DELETE CASCADE;

ALTER TABLE "Position_history" ADD FOREIGN KEY ("Position_ID") 
REFERENCES "Position" ("Position_ID") ON DELETE CASCADE;

ALTER TABLE "Transaction" ADD FOREIGN KEY ("Transaction_type_ID") 
REFERENCES "Transaction_type" ("Transaction_type_ID") ON DELETE CASCADE;

ALTER TABLE "Transaction" ADD FOREIGN KEY ("Invoice_ID") 
REFERENCES "Invoice" ("Invoice_ID") ON DELETE SET NULL;

ALTER TABLE "Car_dealer" ADD FOREIGN KEY ("Address_ID") 
REFERENCES "Address" ("Address_ID") ON DELETE CASCADE;

ALTER TABLE "Employee_stats" ADD FOREIGN KEY ("Employee_ID") 
REFERENCES "Employee" ("Employee_ID") ON DELETE CASCADE;

ALTER TABLE "Employee" ADD FOREIGN KEY ("Login_credentials_ID")
REFERENCES "Login_credentials" ("Login_credentials_ID") ON DELETE SET NULL;

-- TRIGGERS

CREATE OR REPLACE FUNCTION update_employee_stats() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO "Employee_stats" ("Year", "Month", "Employee_ID", "Sales_sum")
  VALUES (EXTRACT (YEAR FROM NEW."Date"), EXTRACT (MONTH FROM NEW."Date"), NEW."Employee_ID", NEW."Value")
  ON CONFLICT ("Year", "Month", "Employee_ID")
  DO UPDATE SET "Sales_sum" = "Employee_stats"."Sales_sum" + NEW."Value";
  
  IF NEW."Value" < 0 THEN
    RAISE EXCEPTION 'Value cannot be negative';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_employee_stats
AFTER INSERT ON "Transaction"
FOR EACH ROW
EXECUTE FUNCTION update_employee_stats();

CREATE OR REPLACE FUNCTION insert_invoice()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW."Issue_date" IS NULL THEN
    NEW."Issue_date" := CURRENT_DATE;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_insert_invoice
BEFORE INSERT ON "Invoice"
FOR EACH ROW
EXECUTE FUNCTION insert_invoice();

CREATE OR REPLACE FUNCTION insert_position_history()
RETURNS TRIGGER AS $$
DECLARE
  salary      integer;
  min_salary  integer;
  max_salary  integer;
BEGIN
  IF NEW."Date_end" IS NULL THEN
    SELECT "Salary"
    INTO salary
    FROM "Employee" 
    WHERE "Employee"."Employee_ID" = NEW."Employee_ID";
    IF salary IS NULL THEN
      SELECT "Min_salary", "Max_salary"
      INTO min_salary, max_salary
      FROM "Position"
      WHERE "Position"."Position_ID" = NEW."Position_ID";
      UPDATE "Employee" SET "Salary" = ROUND(RANDOM()*(max_salary - min_salary) + min_salary)
      WHERE "Employee_ID" = NEW."Employee_ID";
    END IF;
  END IF;
  UPDATE "Position_history" SET "Date_end" = NEW."Date_start" - INTERVAL '1 day'
  WHERE "Employee_ID" = NEW."Employee_ID" AND "Date_end" IS NULL;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_insert_position_history
BEFORE INSERT ON "Position_history"
FOR EACH ROW
EXECUTE FUNCTION insert_position_history();

CREATE OR REPLACE FUNCTION delete_car_dealer()
RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM "Address" WHERE "Address_ID" = OLD."Address_ID";
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_delete_car_dealer
AFTER DELETE ON "Car_dealer"
FOR EACH ROW
EXECUTE FUNCTION delete_car_dealer();

CREATE OR REPLACE FUNCTION insert_car()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW."Mileage" < 0 THEN
    RAISE EXCEPTION 'Mileage cannot be negative';
  END IF;

  IF NEW."Price" < 0 THEN
    RAISE EXCEPTION 'Price cannot be negative';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_insert_car
BEFORE INSERT OR UPDATE ON "Car"
FOR EACH ROW
EXECUTE FUNCTION insert_car();

CREATE OR REPLACE FUNCTION insert_address()
RETURNS TRIGGER AS $$
BEGIN
  IF LENGTH(NEW."Postcode") != 5 THEN
    RAISE EXCEPTION 'Postcode must be exactly 5 digits. Got: %', NEW."Postcode";
  END IF;

  IF NEW."Street_number" < 0 THEN
    RAISE EXCEPTION 'Street number cannot be negative';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_insert_address
BEFORE INSERT OR UPDATE ON "Address"
FOR EACH ROW
EXECUTE FUNCTION insert_address();

CREATE OR REPLACE FUNCTION insert_client()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW."Mail" NOT LIKE '%@%' THEN
    RAISE EXCEPTION 'Incorrect mail format';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_insert_client
BEFORE INSERT OR UPDATE ON "Client"
FOR EACH ROW
EXECUTE FUNCTION insert_client();

CREATE OR REPLACE FUNCTION insert_employee()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW."Salary" < 0 THEN
    RAISE EXCEPTION 'Salary cannot be negative';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_insert_employee
BEFORE INSERT OR UPDATE ON "Employee"
FOR EACH ROW
EXECUTE FUNCTION insert_employee();

CREATE OR REPLACE FUNCTION insert_position()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW."Min_salary" < 0 OR NEW."Max_salary" < 0 THEN
    RAISE EXCEPTION 'Salary cannot be negative';
  END IF;

  IF NEW."Min_salary" > NEW."Max_salary" THEN
    RAISE EXCEPTION 'Minimum salary cannot be greater than maximum salar';
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_insert_position
BEFORE INSERT OR UPDATE ON "Position"
FOR EACH ROW
EXECUTE FUNCTION insert_position();

CREATE OR REPLACE FUNCTION delete_employee()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE "Employee" SET "Employee_status_ID" = (
    SELECT "Employee_status_ID" FROM "Employee_status"
    WHERE "Status_name" = 'Inactive'
  )
  WHERE "Employee_ID" = OLD."Employee_ID";
  UPDATE "Position_history" SET "Date_end" = CURRENT_DATE
  WHERE "Employee_ID" = OLD."Employee_ID" AND "Date_end" IS NULL;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tgr_delete_employee
BEFORE DELETE ON "Employee"
FOR EACH ROW
EXECUTE FUNCTION delete_employee();

-- FUNCTIONS

CREATE OR REPLACE FUNCTION get_user_stats(user_id integer)
RETURNS TABLE (
  cars_sold bigint,
  total_profit bigint,
  active_since date
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    -- cars sold
    (SELECT COUNT(*) FROM "Transaction" t
    JOIN "Transaction_type" tt ON t."Transaction_type_ID" = tt."Transaction_type_ID"
    WHERE t."Employee_ID" = user_id
    AND tt."Name" = 'Purchase'),

    -- total profit
    (SELECT SUM("Value") FROM "Transaction"
    WHERE "Employee_ID" = user_id),

    -- active sinces
    (SELECT MIN("Date") FROM "Transaction"
    WHERE "Employee_ID" = user_id);

END;
$$ LANGUAGE plpgsql;
